import Head from 'next/head'
import { Inter } from 'next/font/google'
import Hero from '@/components/page-sections/home/Hero'
import LoadingScreen from '@/components/page-sections/home/LoadingScreen'
import { useEffect, useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [loadScreen,setLoadScreen] = useState(true)
  useEffect(()=>{
    setTimeout(()=>setLoadScreen(false),2500)
  })

    

  return (
    <>
      <Head>
        <title>Nana Kwasi Asante</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className}`}>
        <LoadingScreen shouldLoad={loadScreen}/>
        <Hero/>
      </main>
    </>
  )
}
